// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkec_yMHJ55xt4p89MN6Iju_qtAeTVumI',
    appId: '1:232744207953:web:80e5a4c7b53f3154c91a70',
    messagingSenderId: '232744207953',
    projectId: 'hackversemedcave',
    authDomain: 'hackversemedcave.firebaseapp.com',
    storageBucket: 'hackversemedcave.firebasestorage.app',
    measurementId: 'G-5Q8XMZKLHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVDxa3agyjUHDkpvzwE-Zw6q94qO1UZM8',
    appId: '1:232744207953:android:933fb499e3ea9c38c91a70',
    messagingSenderId: '232744207953',
    projectId: 'hackversemedcave',
    storageBucket: 'hackversemedcave.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpE2TKIPsb3rlqeR0i0NWAUHHaCWqN4vM',
    appId: '1:232744207953:ios:de4cc2bdeb3477efc91a70',
    messagingSenderId: '232744207953',
    projectId: 'hackversemedcave',
    storageBucket: 'hackversemedcave.firebasestorage.app',
    iosBundleId: 'com.example.medcave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpE2TKIPsb3rlqeR0i0NWAUHHaCWqN4vM',
    appId: '1:232744207953:ios:de4cc2bdeb3477efc91a70',
    messagingSenderId: '232744207953',
    projectId: 'hackversemedcave',
    storageBucket: 'hackversemedcave.firebasestorage.app',
    iosBundleId: 'com.example.medcave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkec_yMHJ55xt4p89MN6Iju_qtAeTVumI',
    appId: '1:232744207953:web:4a8f07cd847355c8c91a70',
    messagingSenderId: '232744207953',
    projectId: 'hackversemedcave',
    authDomain: 'hackversemedcave.firebaseapp.com',
    storageBucket: 'hackversemedcave.firebasestorage.app',
    measurementId: 'G-2XG60RB50W',
  );
}